### ISSUE TITLE
FormArray wrapper doesn't support second options parameter of Angular

### ISSUE THREAD

**Issue by abierbaum** [ngneat/reactive-forms#104]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

The reactive-forms wrapper for FormArray does not support the `options` argument allowed by the underlying Angular FormArray.

As an example, see `FormArray.push`: https://github.com/ngneat/reactive-forms/blob/master/projects/ngneat/reactive-forms/src/lib/formArray.ts

This should include a second argument to pass options to the super class as documented: https://angular.io/api/forms/FormArray#push

## Expected behavior

All FormArray methods should support the same parameters as the underlying Angular FormArray

## Minimal reproduction of the problem with instructions

None.  This is an interface bug.

## What is the motivation / use case for changing the behavior?

This is needed to allow modifying the FormArray while preventing valueChanges from being emitted.

## Environment

<pre><code>
Angular version: 12.2.2
reactive-forms: 1.7.5 (and master)

Browser: N/A

**Comment by NetanelBasal** [comment]
Fixed in v2
