### ISSUE TITLE
Complex typings broke auto type definition

### ISSUE THREAD

**Issue by xaosaki** [ngneat/reactive-forms#106]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
This line breaks overrides.
https://github.com/ngneat/reactive-forms/blob/8675a4f723479b08a8810a9cd2f255243cc5cff7/projects/ngneat/reactive-forms/src/lib/formGroup.ts#L129
Compiler go in to 1 or last override
![image](https://user-images.githubusercontent.com/28115571/132366275-f5c471dd-6b10-4807-a49b-0a4550ea4225.png)
![image](https://user-images.githubusercontent.com/28115571/132365699-9c8c7cad-dbf5-459b-b73b-48d8609a0fe7.png)

## Expected behavior

Compiler should go in 3 override. If i comment linked line all will be ok.
![image](https://user-images.githubusercontent.com/28115571/132365801-0b598c1e-61e9-4181-bcf9-6608c0c51f17.png)

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-ivy-22wuvb?file=src%2Fapp%2Fapp.component.ts

For easy investigation i created file https://stackblitz.com/edit/angular-ivy-22wuvb?file=simple.ts its a simplest version with reproduction case.

## Environment
I run stackblitz project in PhpStorm 2021.2.1

May have the same roots that https://github.com/ngneat/reactive-forms/issues/103

**Comment by NetanelBasal** [comment]
I'm not sure what you mean. There are no errors in stackblitz:

![image](https://user-images.githubusercontent.com/6745730/132633230-4f1eb052-bf8e-49ff-8dbf-4d8d67466689.png)

**Comment by xaosaki** [comment]
You need download stackblitz example and open it in IDE with advanced typescript support. ex WebStorm or PhpStorm.

**Comment by NetanelBasal** [comment]
Yes.

VsCode works fine:

![image](https://user-images.githubusercontent.com/6745730/132642312-3db5d007-06db-4997-80d3-9d9d17f8e6b8.png)

**Comment by xaosaki** [comment]
Ок, i looked at typescriptlang.org/play and there was correct to. I will create issue in JetBrains tracker.

P.S. Can you self look at #103 ?

**Comment by NetanelBasal** [comment]
I asked from the one that added this feature.
