### ISSUE TITLE
Is is safe to install with --legacy-peer-deps

### ISSUE THREAD

**Issue by urielzen** [ngneat/reactive-forms#108]
I have angular V10 in my project.
When trying to run 
`npm i @ngneat/reactive-forms`
I get this error
```
Could not resolve dependency:
peer @angular/core@">= 12.2.3" from @ngneat/reactive-forms@2.0.0
```

The documentation says that the package is compatible with angular V8+, but that is inconsistent with the error above.

Please let me know if it is ok to install with `--legacy-peer-deps`

**Comment by NetanelBasal** [comment]
If you don't see any compiler issues, you can use the current version.
