### ISSUE TITLE
GetRawValue() doesn't return nested disabled values

### ISSUE THREAD

**Issue by jingfee** [ngneat/reactive-forms#116]
### Is this a regression?

Yes

### Description

I recently tried to update from 1.7.5 to 3.1.3 and found a bug within my application which I could trace down to getRawValue() not working as intended.

Examples when it works and doesn't work. the children-formarray is disable in these cases. For simplicitys sake the formgroups in these examples are visualized as json-objects.

This one works:

```
{
 "value": "foo",
 "children": [
  {
   value: "bar"
  }
 ]
}
```

This one doesn't work:

```
[
 {
  "value": "foo",
  "children": [
   {
    value: "bar"
   }
  ]
 }
]
```

In the second example I only get the "value: 'foo'" when calling getRawValue() and the children-formarray is completely missing. Downgrading back to 1.7.5 and it works as expected again.

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
Share your code, please.

**Comment by jingfee** [comment]
> Share your code, please.

I'm trying to replicate in a Stackblitz 🙂
