### ISSUE TITLE
Upgrade is hard and refactoring too big

### ISSUE THREAD

**Issue by jogelin** [ngneat/reactive-forms#119]
I am writing this issue to share about the upgrade from v1.7.5 to v3.

We are using this library since the beginning in our mono repo and we really liked the fact that we could make our forms typed.

We are trying to keep our repo up to date but with the last upgrade but we investigated what will be the cost of refactoring our forms and it is really too much.

In fact, being forced to create a new type with specific AbtractControl each time we have a complex object is impacting us too much.

And because the upgrade cannot be incremental, we decided to wait until Angular will make its own version. Th the imports will not be the same and we could upgrade step by step.

And now we would like to upgrade to Angular v13 but you don't propose a v1.x compatible version :(

What could we do? Removing simply your library?

**Comment by NetanelBasal** [comment]
> In fact, being forced to create a new type with specific AbtractControl each time we have a complex object is impacting us too much.

I'm not sure what you mean here.
