### ISSUE TITLE
possible bug using formBuilder

### ISSUE THREAD

**Issue by MilesHeise** [ngneat/reactive-forms#32]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

controls created using formBuilder do not appear to have all the features that they should

```
        this.formGroup = this.formBuilder.group({
            categoryKey: null,
            description: null
        });
        
        // does not work
        this.formGroup.controls.categoryKey.errors$.subscribe()

        // works
        const control = new FormControl('');
        control.errors$.subscribe(errors => {});
```
In this sample shown, using a directly created form control by copy pasting from the docs, the `errors$` observable is present. However, trying to access the `errors$` on my control created using formBuilder gives me a TS linting error saying it doesn't exist and suggesting the vanilla errors object

## Expected behavior

As far as I can tell from the docs, it sounds like controls made with formBuilder should also be fully featured. I checked other items like `disabled$` etc and none of them appear on the item made with formBuilder

## Minimal reproduction of the problem with instructions

just create something with formBuilder and try to access items like `errors$`

## What is the motivation / use case for changing the behavior?

To fix what appears to be broken behaviour (I apologize if I am just doing something wrong here or misinterpreting how it should work, in which case possibly a clarification added to the docs could help instead?)

## Environment

<pre><code>
Angular version: 7.2.15
TS version: 3.2.4

Browser:
- [x] Chrome (desktop) version 84
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by tehshin** [comment]
In the examples that are available in the readme they cast the controls to FormControl that is provided by the lib.

`const address = group.getControl('name') as FormGroup<Profile['address']>;`

I am not sure if it is intended like this, but it does work: https://stackblitz.com/edit/angular-ivy-tpmydz

**Comment by MilesHeise** [comment]
interesting, I'll certainly give that a shot, thanks!

**Comment by NetanelBasal** [comment]
Yes, this is the current behavior. See issue [32](https://github.com/ngneat/reactive-forms/issues/32). You're welcome to add this to the form builder section.

**Comment by danzrou** [comment]
#23
