### ISSUE TITLE
FormArray helpers to remove controls.

### ISSUE THREAD

**Issue by MarioArnt** [ngneat/reactive-forms#40]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

Hello, 

I'm using the lib and it would be great if there was more methods to remove controls from `FormArray`

Currently there's only a `removeAt(index: number)` method (inherited from @angular/forms) which is not very convenient to remove a control by value or by a given predicate. 

I am thinking about something like this in the [FormArray class](https://github.com/ngneat/reactive-forms/blob/master/projects/ngneat/reactive-forms/src/lib/formArray.ts):

```typescript
removeWhen(predicate: (value: T) => boolean) {
  for (let i = 0; i < this.length; ++i) {
    if (predicate(this.at(i).value)) {
      this.removeAt(i);
    }
  }
};

remove(value: T) {
  this.removeWhen((v) => v === value);
};
```

I can make a PR if you are interested by such a feature 🚀 

Thanks for your work 👍 

BTW, the link to the repo is outdated on NPM, you should [update repo field](https://github.com/ngneat/reactive-forms/blob/master/projects/ngneat/reactive-forms/package.json)

**Comment by NetanelBasal** [comment]
Sounds good. We just need to think about a better name. You can submit a PR.

**Comment by danzrou** [comment]
I suggest providing the whole control in the predicate as we might want to consider disabled or other control states to find it

**Comment by MarioArnt** [comment]
@NetanelBasal I created PR #41 for this, feel free to suggest other names for the new methods

Good point @danzrou ! I provided the whole control so it is possible to use any property (disable, dirty, status etc...) in the predicate
