### ISSUE TITLE
FormControl asyncValidator not Correctly Overriden

### ISSUE THREAD

**Issue by jonrwads** [ngneat/reactive-forms#44]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Trying to upgrade to Angular 10 and on build I get this error
`ERROR in node_modules/@ngneat/reactive-forms/lib/formControl.d.ts:7:14 - error TS2610: 'asyncValidator' is defined as an accessor in class 'FormControl', but is overridden here in 'FormControl<T, E>' as an instance property.`

## Expected behavior

I would expect it to build without the error above

## Minimal reproduction of the problem with instructions

After upgrading to Angular 10, simply try to run the app.

## Environment

<pre><code>
Angular version: 10.1.0</code></pre>

## Others 
This was asked in a different issue and I was told it was unrelated so I thought to open up a new issue for any incoming PRs.  I have not had the opportunity to dive too deply in this but I am wondering if the asyncValidator needs to be in the FormControl class or if it could just use the inherited property.

Thanks again for your quick response on the original question.

**Comment by NetanelBasal** [comment]
Do you want to create a PR?

**Comment by jonrwads** [comment]
Just barely got back to this and noticed you had resolved this.  Thank you for your quick resolution.  I wasn't around this last week to contribute this fix.
