### ISSUE TITLE
using .setErrors doesn't trigger .errors$ to next()

### ISSUE THREAD

**Issue by Burgov** [ngneat/reactive-forms#45]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Setting an error to a control using `.setErrors()` does not trigger a new value to be emitted from `.errors$`.

## Expected behavior

calling `.setErrors()` should trigger `.errors$` to emit

## What is the motivation / use case for changing the behavior?

We're calling `.setErrors()` based on a response from the API. Currently, this lib only checks for changes in errors directly after valueChanges, but since the API call is async, valueChanges is never triggered.

## Environment

<pre><code>
Angular version: 9.1.9

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by NetanelBasal** [comment]
Do you want to create a PR?

**Comment by Burgov** [comment]
@NetanelBasal https://github.com/ngneat/reactive-forms/pull/47
