### ISSUE TITLE
Additional data passed through form

### ISSUE THREAD

**Issue by criskrzysiu** [ngneat/reactive-forms#49]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Expected behavior
I would like to propose ability to pass some custom observable data to form to be able to pass it through form control. It is really useful if that data is dependent on something in form model and we want to for example create that form in dedicated service.
```html
  <kendo-multiselect
                #list
                [data]="control.data$ | async"
                [filterable]="true"
                textField="text"
                valueField="value"
                placeholder="T-shirt size"
               [formControl]=[control]
   >
    </kendo-multiselect>
```

and in service 

```typescript
 createControl(){
   const control = new FormControl<number>(undefined);
   control.passData(someObservableData$);
}
```

here it is a bit simplified and the use cases is not very visible but imagine this data being dependent on other form values from for example parent form. And some validations and disabled states also also depend on that data in other field etc. 

I'm currently working on such form and such feature would be really useful and allow me to do everything much more neatly.

It become really usefull if data is used for a field in model that is in form array and is dependent on field from parent form group.

Just not sure if it should be observable or just "any" and let user decide what is needed.

**Comment by NetanelBasal** [comment]
I am not sure what is the use case and the functionality. Can you provide a complete example, please?

**Comment by criskrzysiu** [comment]
@NetanelBasal It will take some time but I already have use cases in my project so I will try to write something based on that.

**Comment by itayod** [comment]
@criskrzysiu any progress with the usecase?
