### ISSUE TITLE
Type FormGroup is not assignable to type AbstractControl

### ISSUE THREAD

**Issue by Benny739** [ngneat/reactive-forms#51]
Hi,

in various places I'm getting following error:

> Type 'FormGroup<any, any>' is not assignable to type 'AbstractControl<any>'.

It happens for example when I'm using nested FormGroups. The example from the docs also produces this error.

```
import { FormGroup } from '@ngneat/reactive-forms';

interface Profile {
  firstName: string;
  lastName: string;
  address: {
    street: string;
    city: string;
  };
}

const profileForm = new FormGroup<Profile>({
  firstName: new FormControl(''),
  lastName: new FormControl(''),
  address: new FormGroup({
    street: new FormControl(''),
    city: new FormControl('')
  })
});
```

> Type 'FormGroup<{ street: string; city: string; }, ValidationErrors>' is not assignable to type 'AbstractControl<{ street: string; city: string; }>'.
  Types of property 'get' are incompatible.
    Type '{ <K1 extends "street" | "city">(path?: [K1] | undefined): AbstractControl<{ street: string; city: string; }[K1]>; <K1 extends "street" | "city", K2 extends keyof { street: string; city: string; }[K1]>(path?: [...] | undefined): AbstractControl<...>; <K1 extends "street" | "city", K2 extends keyof { ...; }[K1], K3 e...' is not assignable to type '(path: string | (string | number)[]) => AbstractControl | null'.
      Types of parameters 'path' and 'path' are incompatible.
        Type 'string | (string | number)[]' is not assignable to type '[any] | undefined'.
          Type 'string' is not assignable to type '[any] | undefined'

**Comment by danzrou** [comment]
Are you using strict mode in TS?

**Comment by Benny739** [comment]
Yes.

**Comment by danzrou** [comment]
#26

**Comment by danzrou** [comment]
I am not able to reproduce it on latest version. (which was released today)

Can you check?
