### ISSUE TITLE
FormControl typed with object doesn't expose enabledWhile (and others) as opposed to one typed with primitives

### ISSUE THREAD

**Issue by CesarD** [ngneat/reactive-forms#63]
I have a typed `FormGroup` that contains a few `FormControls`, some of them bind to primitive types like `number` or `string`, and others to objects of my app.

Those `FormControls` binded to objects are not showing properties like `enabledWhile` or `disabledWhile` when I try to call them by mean of `this.formGroup.getControl('myObject').enabledWhile(...)`.

Is this on purpose or not? If so, why?

**Comment by itayod** [comment]
@CesarD could you please add here the complete code snippet of your code?

**Comment by CesarD** [comment]
Hi @itayod.
Well, it's basically just as I described it: instead of making a FormControl<number>, I made a FormControl<Customer> on a FormGroup, and there's where the inconsistence shows up (unless that's by design, idk)

I could get you more details by tomorrow if needed... Let me know.

**Comment by itayod** [comment]
@CesarD yes, it is by design, you will need to "cast" the control or use `ControlsOf` utility as follows:
```ts
new FormGroup<ControlsOf<Address>>({
  ...
})
```
this should give you the correct type annotation.

**Comment by CesarD** [comment]
So if I have, say:

```typescript
export class DataForm {
  userId: string;
  vessel: Vessel;
}
```
and then 

```typescript
this.formData = new FormGroup<DataForm>({
  userId: new FormControl<string>(null),
  vessel: new FormControl<Vessel>(null)
});
```

should I change it by something like this?

```typescript
this.formData = new FormGroup<DataForm>({
  userId: new FormControl<string>(null),
  vessel: new FormControl<ControlsOf<Vessel>>(null)
});
```

I just wrote it on my code and it's already yelling:

`TS2322: Type 'FormControl<ControlsOf<Vessel, {}>, any>' is not assignable to type 'AbstractControl<Vessel, any>'`

What am I missing?

**Comment by simon-hv** [comment]
Hey!

Maybe if you try:

```javascript
this.formData = new FormGroup<ControlsOf<DataForm>>({
  userId: new FormControl<string>(null),
  vessel: new FormGroup<ControlsOf<Vessel>>(null)
})
```

Then you can do:
```javascript
this.formData.getControl('vessel').enabledWhile(...)
```

I haven't had the time to test so I'm not sure about that at all, but maybe it can help you.

**Comment by CesarD** [comment]
>
> ```js
> this.formData = new FormGroup<DataForm>({
>   userId: new FormControl<string>(null),
>   vessel: new FormControl<Vessel>(null)
> })
> ```
> 
> and
> 
> ```js
> (formData.getControl('vessel') as FormControl<Vessel>).enabledWhile(...)
> ```
> 

This is what I've been doing so far, but thought it was weird having to cast every single time when it was already typed, so that's the reason of this question :)

**Comment by simon-hv** [comment]
I think this will be improved in future releases as you can see here: https://github.com/ngneat/reactive-forms/issues/23 :)

**Comment by CesarD** [comment]
Ok, so then this is working as designed and it's not just a bug nor me doing something wrong, right?

**Comment by itayod** [comment]
@CesarD there are several ways you can solve it:
```ts

export class DataForm {
  userId: string;
  vessel: { id: string; name: string; };
}

const form = new FormGroup<ControlsOf<DataForm>>({
  userId: new FormControl(), // -> FormControl<string>
  vessel: new FormGroup<ControlsOf<DataForm['vessel']>>({ id: new FormControl(), name: new FormControl() })
});

// you can also override it like this:
const form2 = new FormGroup<ControlsOf<DataForm, { vessel: FormControl<DataForm['vessel']>}>>({
  userId: new FormControl(), // -> FormControl<string>
  vessel: new FormControl() // -> FormControl<DataForm['vessel']>
});

// without ControlsOf it will be resolved as AbstractControl:
const form3 = new FormGroup<DataForm>({
  userId: new FormControl(), // -> FormControl<string>
  vessel: new FormControl() // -> Abstract<DataForm['vessel']>
});

// alternatively we can declare the control type here: 
export class ControlsOfDataForm {
  userId: string;
  vessel: FormControl<{ id: string; name: string; }>;
}

const form4 = new FormGroup<ControlsOfDataForm>({
  userId: new FormControl(), // -> FormControl<string>
  vessel: new FormControl() // -> FormControl<DataForm['vessel']>
});

```

Pick the one you are most comfortable with :) but yes, it is not a bug.

Let me know if you have worked it out and we can close this issue.

**Comment by CesarD** [comment]
I see. Thanks for the compilation of examples.
I guess I'll stick with the casting as I was currently on, and will wait for the improvement that helps on this matter.

Thanks again!
