### ISSUE TITLE
Saving disabled controls with persist method

### ISSUE THREAD

**Issue by simon-hv** [ngneat/reactive-forms#64]
Hi everyone!

I'm using the `persist` method to store the `FormGroup` to the sessionStorage, but it doesn't store disabled controls (I don't know if there is a reason for that). 

Right now, I found a workaround by creating my own class implementing the `PersistManager` interface but I was wondering if there was any drawbacks to use `value$` instead of `valueChanges` in the line below?
This would allow to integrate the disabled controls when we use the `persist` method.

https://github.com/ngneat/reactive-forms/blob/f3d7b92c854c61517b6f0097249d4c81a9e0a573/projects/ngneat/reactive-forms/src/lib/control-actions.ts#L148

Thanks!

**Comment by NetanelBasal** [comment]
You are right. I don't know if there are drawbacks, but I'd definitely make it configurable through the API. Do u want to create a PR? @Coly010, are you doing it?

**Comment by stefanoww** [comment]
@NetanelBasal I can take it.

**Comment by NetanelBasal** [comment]
Ok, thanks

**Comment by yntelectual** [comment]
@stefanoww  Thanks for the MR! @NetanelBasal do you plan to make a new release anytime soon? Or is there a chance to publish this as `next` in npm?
