### ISSUE TITLE
Fails to compile

### ISSUE THREAD

**Issue by grosch** [ngneat/reactive-forms#65]
## I'm submitting a...

<pre><code>
[X] Bug report  
</code></pre>

## Current behavior

When I build my project I'm getting compiler errors from the controls in this package. For example, this is the first one that appears:

> Error: node_modules/@ngneat/reactive-forms/lib/formControl.d.ts:20:9 - error TS2416: Property 'asyncValidator' in type 'FormControl<T, E>' is not assignable to the same property in base type 'FormControl'.
Type 'AsyncValidatorFn<T, any> | null' is not assignable to type 'AsyncValidatorFn | null'.
Type 'AsyncValidatorFn<T, any>' is not assignable to type 'AsyncValidatorFn'.
Types of parameters 'control' and 'control' are incompatible.
Type 'AbstractControl' is missing the following properties from type 'AbstractControl<T, any>': touch$, dirty$, disabled$, enabled$, status$
>  
> 20 get asyncValidator(): AsyncValidatorFn | null;

## Minimal reproduction of the problem with instructions

[example.zip](https://github.com/ngneat/reactive-forms/files/5705016/example.zip)

## Environment

<pre><code>
Angular version: 11.0.0
For Tooling issues:
- Node version: v15.3.0
- Platform:  mac BigSur 11.1

Others:

</code></pre>
I saw the pinned issue, but while similar I think this is different as I'm just simply doing a build with your package included.

**Comment by itayod** [comment]
@grosch which version do you use? could you post here the code snippet that fails?

**Comment by grosch** [comment]
I'm using 1.5.  I attached an example project, but here's the app.component.ts

```typescript
import {FormBuilder} from '@ngneat/reactive-forms'

interface Data {
    title: string
    chapters: string[]
}

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.scss']
})
export class AppComponent {
    readonly formGroup = this.fb.group<Data>({
        title: ['', Validators.required],
        chapters: this.fb.array<string>([], Validators.min(3))
    })

    constructor(private readonly fb: FormBuilder) {
    }
}
```

**Comment by itayod** [comment]
@grosch please upgrade to the latest version and see if it works.

**Comment by grosch** [comment]
Looks like 1.5.1 fixed it.
