### ISSUE TITLE
Unable to pass options to updateValueAndValidity when calling setValidators

### ISSUE THREAD

**Issue by ciesielskico** [ngneat/reactive-forms#66]
## I'm submitting a...

<pre><code>
[x] Regression
[x] Bug report  
</code></pre>

## Current behavior

With regular Angular forms calling `setValidators` does not automatically call `updateValueAndValidity`.
We had to manually call `updateValueAndValidity` and had the ability to pass options, like `{onlySelf: true}` to that method.

## Expected behavior

My code broke after migrating to this library, since I used to call `updateValueAndValidity` with additional options.

The `setValidators` method should therefore be extended by an optional parameter `options`, which is passed straight into `updateValueAndValidity`.

https://github.com/ngneat/reactive-forms/blob/6aa3994abd50ce71b634cb58188e7e81f2f23946/projects/ngneat/reactive-forms/src/lib/formGroup.ts#L227

I guess the same behavior applies to `clearValidators`.

## Environment

<pre><code>
Angular version: 8

Browser:
- [x] Chrome (desktop) version XX

**Comment by itayod** [comment]
@ciesielskico sounds like we do need it, would you like to create a pr for that?

**Comment by stefanoww** [comment]
I would like to take it if it's free.

**Comment by NetanelBasal** [comment]
@stefanoww it's all yours.
