### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by andreialecu** [ngneat/reactive-forms#75]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I'm investigating some memory bloat in a large form, and noticed that a lot of the form controls are being retained when navigating to/back to the page that contains it, as evidenced by the memory profiler in chrome:

<img width="875" alt="Screenshot 2021-01-21 at 13 34 47" src="https://user-images.githubusercontent.com/697707/105345852-6f713900-5bed-11eb-8ced-0b9791c1145b.png">

While looking through the code:
https://github.com/ngneat/reactive-forms/blob/2a564549ac653b20db298f2bc01739b7ab164f84/projects/ngneat/reactive-forms/src/lib/formControl.ts#L43-L54

It appears that none of these subscriptions or their Subjects are ever completed.

In the case of my form it looks like around 50000 observables are leaked every time I navigate to the specific tab that contains the form.

Note that I'm unsubscribing from the ones that I'm using, but I'm seeing leaks of others I don't use at all, such as `errors$`

## Expected behavior

Subscriptions should be completed somehow.

## Minimal reproduction of the problem with instructions

Should be reproducible in any app by default as long as the form is being re-created. Such as wrapping it in an `*ngIf`. I can't find a working stackblitz or I would've added a repro myself.

## What is the motivation / use case for changing the behavior?

Prevents memory leaks.

## Environment

<pre><code>
Angular version: 11.1.0

**Comment by NetanelBasal** [comment]
It's your responsibility to unsubscribe, like in any other observable.

**Comment by andreialecu** [comment]
>It's your responsibility to unsubscribe, like in any other observable.

Please re-read the issue text. I already addressed that concern.

You can use this patch on `master` to see it leak.

```patch
diff --git a/src/app/app.component.html b/src/app/app.component.html
index c226012..b2800e8 100644
--- a/src/app/app.component.html
+++ b/src/app/app.component.html
@@ -17,3 +17,6 @@
 
   {{ profileForm.value | json }}
 </form>
+
+<button (click)="testVisible = !testVisible">Toggle form</button>
+<app-test-form *ngIf="testVisible"></app-test-form>
diff --git a/src/app/app.component.ts b/src/app/app.component.ts
index ea383a5..621130d 100644
--- a/src/app/app.component.ts
+++ b/src/app/app.component.ts
@@ -22,6 +22,8 @@ interface Profile {
   styleUrls: ['./app.component.scss']
 })
 export class AppComponent {
+  testVisible = false;
+
   profileForm = new FormGroup<Profile>({
     firstName: new FormControl(''),
     lastName: new FormControl(''),
diff --git a/src/app/test-form/test-form.component.ts b/src/app/test-form/test-form.component.ts
index b6a10f3..1e06f8a 100644
--- a/src/app/test-form/test-form.component.ts
+++ b/src/app/test-form/test-form.component.ts
@@ -1,7 +1,6 @@
 import { Component } from '@angular/core';
 
-import { FormControl, FormGroup, FormArray } from '@angular/forms';
-
+import { FormControl, FormGroup } from '@ngneat/reactive-forms';
 @Component({
   selector: 'app-test-form',
   template: `
@@ -11,11 +10,9 @@ import { FormControl, FormGroup, FormArray } from '@angular/forms';
   `
 })
 export class TestFormComponent {
-  control: FormControl = new FormControl();
+  group: FormGroup = new FormGroup({ input: new FormControl("test") });
 
   constructor() {
-    const control = new FormArray([]);
-    control.setControl(0, new FormGroup({}));
-    control.at(0).setValue({ name: 'itay' });
+
   }
 }
```

Repeatedly tap the "Toggle Form" button and notice how it leaks:
<img width="1075" alt="Screenshot 2021-01-21 at 14 20 39" src="https://user-images.githubusercontent.com/697707/105350436-d85baf80-5bf3-11eb-978f-09f196215b20.png">

It created 468 additional `Observables` just from a bunch of clicks on it.

**Comment by NetanelBasal** [comment]
Try it by not using this library, and tell me if it's our issue or Angular, please.

**Comment by andreialecu** [comment]
If I replace `@ngneat/forms` with `@angular/forms` it doesn't leak:

<img width="1317" alt="Screenshot 2021-01-21 at 14 24 56" src="https://user-images.githubusercontent.com/697707/105350946-89624a00-5bf4-11eb-9f07-a2ee07cd3b25.png">

Notice how memory usage is exactly the same. 

But this is expected because there are no `Observable`s retained, simply because those are created by this library - and don't even exist with vanilla Angular.

I've pointed out in the initial post exactly why the leak occurs.

**Comment by NetanelBasal** [comment]
Can you create a reproduction on stackblitz, please?

**Comment by KamilSocha91** [comment]
Yup that would be a problem with Subjects, they wont be affected by user unsubscription.

**Comment by andreialecu** [comment]
@NetanelBasal do you have a template to start from? It seems that when I tried using it, StackBlitz fails with `ngcc failed on "@ngneat/reactive-forms"`

**Comment by andreialecu** [comment]
So this is interesting. 

I just noticed something weird in the "Retainers" listing for one of the Observables, which I assumed was related to the LastPass extension that I have installed. 

I then tried disabling the chrome extension and magically the memory leak seems to be gone. 

I guess this might be a false alarm. Will close for now.

**Comment by danzrou** [comment]
Please also note that Angular has known issues regarding memory leaks in Reactive form directives which might be your issue.
Happily, today they released a version which fixes that.
See:

https://github.com/angular/angular/issues/20007
https://github.com/angular/angular/pull/39235

**Comment by andreialecu** [comment]
Yup. I mentioned in the initial posting that I was using angular 11.1.0 - which is the version that included those fixes.

The leak was caused by the chrome extension in this case. 

Since it's supposed to auto fill passwords, it seems to hook into inputs and doesn't detach properly when they're removed from the DOM by angular.
