### ISSUE TITLE
Nested FormBuilder typing issue

### ISSUE THREAD

**Issue by GrzegorzStanczyk** [ngneat/reactive-forms#78]
I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When I'm trying to use FormBuilder a revive interface assignable error.

![image](https://user-images.githubusercontent.com/18703886/107049115-02070000-67ca-11eb-95cd-db466026d99d.png)

## Expected behavior

FormBuilder should work the same as new FormGroup() and new FormArray() instances.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-ivy-fn2teb

## What is the motivation / use case for changing the behavior?

Compatibility to use FormBuilder.

## Environment

<pre><code>
Angular version: ^10.2.4
"@ngneat/reactive-forms": "^1.5.1"

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v15.6.0
- Platform:  Mac

**Comment by NetanelBasal** [comment]
@danzrou wdyt?

**Comment by GrzegorzStanczyk** [comment]
There is also typo in docs interface passed to the FormGroup.
![image](https://user-images.githubusercontent.com/18703886/107125184-9fd0fc80-68a8-11eb-8d57-8b22dae348c7.png)

**Comment by danzrou** [comment]
as the error states - you are creating a group of type `any` while `vat` is required.
it will be easily solved by providing the type explicitly.

```
fb.group<{ test: { vat: string } }>({
        test: fb.group<{vat: string}>({
          vat: fb.control('', Validators.required),
        }),
      });
```

**Comment by GrzegorzStanczyk** [comment]
Yes but with FormGroup it works fine without passing the interface. Aslo when I'm providing e.g. the Profile interface from docs. I would expect that nested form will be inferred like it is with FormGroup and FormArray. If I need to pass nested interfaces deeply, it's tedious labor and redundant for FormBuilder.
