### ISSUE TITLE
touch$ behaviour

### ISSUE THREAD

**Issue by mnmaltsev** [ngneat/reactive-forms#80]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Currently touch$ emits distincted value. 

## Expected behavior

touch$ should emit value on every touch/untouch control events

## What is the motivation / use case for changing the behavior?

New added controls linked to lead control touch$ not receive touch events after first lead control touch event.

**Comment by NetanelBasal** [comment]
Can you provide a code example, please?

**Comment by mnmaltsev** [comment]
repro:
https://stackblitz.com/edit/angular-ivy-e81zmg?file=src%2Fapp%2Fapp.component.html

this behaviour reason:
https://github.com/ngneat/reactive-forms/blob/ac86bf7233a152b5246b1ba6ab373e04902b3820/projects/ngneat/reactive-forms/src/lib/formControl.ts#L47
