### ISSUE TITLE
Migration command does not work: Cannot find module '@phenomnomnominal/tsquery'

### ISSUE THREAD

**Issue by michalsisak** [ngneat/reactive-forms#81]
## I'm submitting a...

<pre><code>
[ X ] Bug report 
</code></pre>

## Current behavior
After a successful install the migration command `ng g @ngneat/reactive-forms:migrate` is not working:
```
An unhandled exception occurred: Cannot find module '@phenomnomnominal/tsquery'
Require stack:
- /Users/person/app/node_modules/@ngneat/reactive-forms/schematics/migrate/index.js
- /Users/person/app/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /Users/person/app/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/index.js
- /Users/person/app/node_modules/@angular/cli/utilities/json-schema.js
- /Users/person/app/node_modules/@angular/cli/models/command-runner.js
- /Users/person/app/node_modules/@angular/cli/lib/cli/index.js
- /Users/person/.nvm/versions/node/v13.8.0/lib/node_modules/@angular/cli/lib/init.js
- /Users/person/.nvm/versions/node/v13.8.0/lib/node_modules/@angular/cli/bin/ng
See "/private/var/folders/jd/4qd93gyj3c9_18z3_yvy3gl80000gn/T/ng-Z1HDXJ/angular-errors.log" for further details.
```

The path is tiny bit changed but only in terms of User name and app folder name. I checked most of those paths and they have the appropriate files.

## Expected behavior
It should run migration command successfully. 

## Minimal reproduction of the problem with instructions
Can't offer repo for reproduction at this point but can try if it will be useful.

## Environment

<pre><code>
Angular version: 11.0.1

For Tooling issues:
- Node version: 13.8.0 (through NVM)
- Platform: Mac

Others:
Part of app contains Angular Element. Could it be relevant?
</code></pre>

**Comment by Jared-Gomes** [comment]
Temporary fix would be to run the command in your root angular directory:
`npm i -D @phenomnomnominal/tsquery`

Then try the migration script as usual:
`ng g @ngneat/reactive-forms:migrate`

I uninstalled the tsquery dependency after the migration was complete.

**Comment by NetanelBasal** [comment]
You'll need to install it manually. I added this info to the docs.
