### ISSUE TITLE
Validators for input type="radio" don't work.

### ISSUE THREAD

**Issue by GrzegorzStanczyk** [ngneat/reactive-forms#82]
Control is valid when Validators.required is set.

## I'm submitting a...
<pre><code>
[X] Bug report
</code></pre>

## Current behavior
Radio control is always valid

## Expected behavior
To work same as native FormControl

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-ivy-emnm3t?file=src%2Fapp%2Fapp.component.ts
Switch FormControl between @angular/forms and @ngneat/reactive-forms and look at valid/invalid status.

## What is the motivation / use case for changing the behavior?
Validate the radio control

## Environment

<pre><code>
Angular version: ^11.0.8

Browser:
- [x] Chrome (desktop) version XX
 
For Tooling issues:
- Node version: v14.16.0
- Platform:  Windows
</code></pre>

**Comment by NetanelBasal** [comment]
<img width="1143" alt="Screen Shot 2021-03-12 at 16 41 18" src="https://user-images.githubusercontent.com/6745730/110955021-d095cd00-8351-11eb-8bac-7a9bcdb50f9a.png">

**Comment by criskrzysiu** [comment]
Hi,
@NetanelBasal what version of Angular did You use and what browser? I tested it on the newest versions of Chrome, Edge, Chrome canary, and Firefox.  I will check Angular 10 tomorrow, maybe that will be it.

**Comment by NetanelBasal** [comment]
I tried it on our playground here.

**Comment by diego-anthony** [comment]
I have the same result in stackblitz, it is more; Same result for input text type, but I replicated it in a local project and it works fine.

**Comment by NetanelBasal** [comment]
Closing this issue for now.
