### ISSUE TITLE
Which is the correct package version? 1.6.1 or 1.7.0 or 1.7.1?

### ISSUE THREAD

**Issue by st-clair-clarke** [ngneat/reactive-forms#84]
My applicaiton package.json shows the following 

       `"@ngneat/reactive-forms": "1.7.0",`

but the package with the exposing of the diff() function is labelled 1.6.1

As a result, I cannot upgrade to get the use of the diff() function.

There seems to be an issue with the package versions.

Cheers

**Comment by NetanelBasal** [comment]
Published 1.7.1.
