### ISSUE TITLE
How do I get the FormGroup's value, not the ControlsValue 

### ISSUE THREAD

**Issue by grosch** [ngneat/reactive-forms#99]
## I'm submitting a...

<pre><code>[X] Support request
</code></pre>

## Current behavior

A `FormGroup`'s `value$` observable emits a `ControlsValue<T>` instead of a `T`.

## Expected behavior

I want to actually get a value of type `T` so that I can do this:

```typescript
this.formGroup.value$.pipe(
    takeUntil(this.unsubscribe$),
).subscribe(x => {
    this.onTouch?.()
    this.onModelChange?.(x)
})
```

That doesn't work though because `x` there isn't actually of type `T`

I'm doing nested forms, and so when this form changes, I pass the value up to the parent's control.

## Environment

<pre><code>Angular version: 12.1.2

Browser:
- [ X] Chrome (desktop) version XX
 
For Tooling issues:
- Node version: v12.19.0
- Platform:  Windows 10
</code></pre>

**Comment by NetanelBasal** [comment]
Please reproduce on stackblitz

**Comment by grosch** [comment]
I tried to create a stackblitz for you but that doesn't work as ngcc fails to run against @ngneat/reactive-forms now.  However, I was able to simplify it down to this example that will show the failure if you paste it into your project:

```typescript
export abstract class DetailForm<T> implements OnInit {
  formGroup!: FormGroup<T>
  public onChange?: (x: T | null) => void

  ngOnInit(): void {
    this.formGroup.value$.subscribe(x => {
      this.onChange?.(x)
    })
  }
}
```

**Comment by grosch** [comment]
Any help you can provide here?

**Comment by NetanelBasal** [comment]
`ControlsValue` is now exported in v2.
